#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the breakingRecords function below.
def breakingRecords(scores,n):
    
    max=min=scores[0]     #set max and min as first element of scores
    c_max=c_min=0               #This c_max and c_max will be used as counter
    for i in range(1,n):
      if scores[i]>max:   #if next score is greater than previous one then increase c_max
        c_max+=1
        max=scores[i]
      if scores[i]<min:   #if next score is smaller than the previous one then increase c_low
        c_min+=1
        min=scores[i]
    return c_max,c_min
        
        


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores,n)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
