#!/bin/python3

# Complete the camelcase function below.
def camelcase(s):
    count=1
    for x in s:
        if x.isupper(): 
            count+=1
    return count

if __name__ == '__main__':

    s = input()

    print(camelcase(s))

    
