#!/bin/python3

class Difference:
    def __init__(self, a):
        self.__elements = a
    maximumDifference=0
    
    
    def computeDifference(self):
        
        for x in a:
            for y in a[1:]:
                if abs(x-y)>Difference.maximumDifference:
                    Difference.maximumDifference=abs(x-y)
	# Add your code here

# End of Difference class

_ = input()
a = [int(e) for e in input().split(' ')]

d = Difference(a)
d.computeDifference()

print(d.maximumDifference)
