#!/bin/python3

for _ in range(int(input())):
    num=int(input())
    if num > 1:
    # check for factors
        for i in range(2, int(num**0.5+1)):
            if (num % i) == 0:
                print("Not prime")
                break
        else:
            print("Prime")
    else:
        print("Not prime")
