#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the divisibleSumPairs function below.
def divisibleSumPairs(n, k, ar):
    tot=0
    for x in range(len(ar)-1):
        for y in range(x+1,len(ar)):
            if (ar[x]+ar[y])>=k and (ar[x]+ar[y])%k==0:
                print(ar[x],ar[y])
                tot+=1
    return tot

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = input().split()

    n = int(nk[0])

    k = int(nk[1])

    ar = list(map(int, input().rstrip().split()))

    result = divisibleSumPairs(n, k, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
