#!/bin/python3

import numpy
numpy.set_printoptions(legacy='1.13')
N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)],int)
print(numpy.mean(A,axis=1))
print(numpy.var(A,axis=0))
print(numpy.std(A,axis=None))
